version: "3.6"
services:
  api:
    build: ./
    image: stock-quote-manager:1.0
    container_name: stock-quote-manager
    restart: unless-stopped
    environment:
      - DB_URL=jdbc:mysql://mysql:3306/bootdb
      - DB_USER=root
      - DB_PWD=root
      - STOCK_MANAGER_URL=http://stockmanager:8080
    ports:
      - "8081:8081"
    depends_on:
      - db
      - stockmanager
    networks:
      - backend

  db:
    image: mysql:8
    restart: unless-stopped
    container_name: mysql
    ports:
      - "3306:3306"
      - "33060:33060"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bootdb
    volumes:
      - backend
    networks:
      - backend

  stockmanager:
    image: lucasvilela/stock-manager
    restart: unless-stopped
    container_name: stockmanager
    networks:
      - backend

networks:
  backend:
    driver: bridge